const fs = require('fs');
const path = require('path');

// Winter Burrow Reddit discussions from requirement documents
const redditPosts = [
  {
    id: '1oxl7hu',
    title: '[HELP & DISCUSSION] Winter Burrow',
    subreddit: 'cozygames',
    description: 'Soft-lock solutions and progress bug help thread with 200+ replies',
    url: 'https://www.reddit.com/r/cozygames/comments/1oxl7hu/help_discussion_winter_burrow/',
    category: 'help',
    tags: ['soft-lock', 'bugs', 'troubleshooting'],
    engagement: 'high'
  },
  {
    id: '1ovh6xj',
    title: 'Winter Burrow Review: Cute and Cosy But Demands Patience',
    subreddit: 'NintendoSwitch',
    description: 'Comprehensive player review and experience mega-thread',
    url: 'https://www.reddit.com/r/NintendoSwitch/comments/1ovh6xj/winter_burrow_review_cute_and_cosy_but_demands/',
    category: 'review',
    tags: ['review', 'gameplay', 'opinions'],
    engagement: 'high'
  },
  {
    id: '1oey51d',
    title: 'Has anyone played the Winter Burrow demo?',
    subreddit: 'CozyGamers',
    description: 'CozyGamers community demo first impressions discussion',
    url: 'https://www.reddit.com/r/CozyGamers/comments/1oey51d/has_anyone_played_the_winter_burrow_demo/',
    category: 'discussion',
    tags: ['demo', 'first-impressions', 'feedback'],
    engagement: 'medium'
  },
  {
    id: '1ovrm35',
    title: 'Winter Burrow. Is there a map in this game?',
    subreddit: 'cozygames',
    description: 'Discussion about the no-map exploration challenge and navigation tips',
    url: 'https://www.reddit.com/r/cozygames/comments/1ovrm35/winter_burrow_is_there_a_map_in_this_game/',
    category: 'help',
    tags: ['map', 'navigation', 'exploration'],
    engagement: 'medium'
  },
  {
    id: '1ovmjea',
    title: 'I have no idea how to progress in Winter Burrow',
    subreddit: 'cozygames',
    description: 'New player progression help and community guidance',
    url: 'https://www.reddit.com/r/cozygames/comments/1ovmjea/i_have_no_idea_how_to_progress_in_winter_burrow/',
    category: 'help',
    tags: ['beginner', 'progression', 'guide'],
    engagement: 'high'
  }
];

// Generate Reddit data structure
const redditData = redditPosts.map(post => ({
  id: post.id,
  title: post.title,
  subreddit: post.subreddit,
  description: post.description,
  url: post.url,
  redditUrl: `https://reddit.com/${post.id}`,
  category: post.category,
  tags: post.tags,
  engagement: post.engagement,
  icon: post.category === 'help' ? '🆘' : post.category === 'review' ? '⭐' : '💬'
}));

// Save to src/data/reddit.ts
const outputPath = path.join(__dirname, '..', 'src', 'data', 'reddit.ts');
const outputContent = `// Auto-generated by scripts/fetch-reddit.js
// Reddit discussions for Winter Burrow

export interface RedditPost {
  id: string;
  title: string;
  subreddit: string;
  description: string;
  url: string;
  redditUrl: string;
  category: 'help' | 'review' | 'discussion';
  tags: string[];
  engagement: 'low' | 'medium' | 'high';
  icon: string;
}

export const redditPosts: RedditPost[] = ${JSON.stringify(redditData, null, 2)};

export default redditPosts;
`;

// Ensure directory exists
const outputDir = path.dirname(outputPath);
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

// Write file
fs.writeFileSync(outputPath, outputContent, 'utf-8');

console.log('💬 Reddit discussion data generated successfully!');
console.log(`   Output: ${outputPath}`);
console.log(`   Posts: ${redditPosts.length}\n`);

redditPosts.forEach((post, index) => {
  console.log(`${index + 1}. ${post.title}`);
  console.log(`   Subreddit: r/${post.subreddit}`);
  console.log(`   Category: ${post.category}`);
  console.log(`   Engagement: ${post.engagement}\n`);
});

console.log('✅ Reddit data saved to src/data/reddit.ts\n');
