const fs = require('fs');
const path = require('path');

// Winter Burrow YouTube videos from requirement documents
const videos = [
  {
    id: 'IARTw2JICZU',
    title: 'Winter Burrow – Announcement Trailer – Nintendo Switch',
    description: 'Official announcement trailer from Nintendo',
    category: 'trailer',
    duration: '1 min',
    source: 'Nintendo Official'
  },
  {
    id: 'Huj0WmMRiMk',
    title: 'Is Winter Burrow Worth Playing? - In-Depth Review',
    description: 'Comprehensive 20-minute review of Winter Burrow gameplay, mechanics, and value',
    category: 'review',
    duration: '20 min',
    source: 'Independent Reviewer'
  },
  {
    id: 'hQqV9lA9A94',
    title: 'WINTER BURROW Gameplay Walkthrough FULL GAME (No Commentary)',
    description: '4K complete playthrough without commentary showing all gameplay elements',
    category: 'walkthrough',
    duration: 'Full Game',
    source: 'Gameplay Channel'
  }
];

// Generate video data structure
const videosData = videos.map(video => ({
  id: video.id,
  title: video.title,
  description: video.description,
  url: `https://www.youtube.com/watch?v=${video.id}`,
  embedUrl: `https://www.youtube.com/embed/${video.id}`,
  thumbnail: `https://img.youtube.com/vi/${video.id}/maxresdefault.jpg`,
  thumbnailMedium: `https://img.youtube.com/vi/${video.id}/mqdefault.jpg`,
  category: video.category,
  duration: video.duration,
  source: video.source
}));

// Save to src/data/videos.ts
const outputPath = path.join(__dirname, '..', 'src', 'data', 'videos.ts');
const outputContent = `// Auto-generated by scripts/fetch-youtube.js
// YouTube videos for Winter Burrow

export interface Video {
  id: string;
  title: string;
  description: string;
  url: string;
  embedUrl: string;
  thumbnail: string;
  thumbnailMedium: string;
  category: string;
  duration: string;
  source: string;
}

export const videos: Video[] = ${JSON.stringify(videosData, null, 2)};

export default videos;
`;

// Ensure directory exists
const outputDir = path.dirname(outputPath);
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

// Write file
fs.writeFileSync(outputPath, outputContent, 'utf-8');

console.log('🎬 YouTube video data generated successfully!');
console.log(`   Output: ${outputPath}`);
console.log(`   Videos: ${videos.length}\n`);

videos.forEach((video, index) => {
  console.log(`${index + 1}. ${video.title}`);
  console.log(`   ID: ${video.id}`);
  console.log(`   Category: ${video.category}`);
  console.log(`   Duration: ${video.duration}\n`);
});

console.log('✅ Videos data saved to src/data/videos.ts\n');
