// Auto-generated by scripts/fetch-reddit.js
// Reddit discussions for Winter Burrow

export interface RedditPost {
  id: string;
  title: string;
  subreddit: string;
  description: string;
  url: string;
  redditUrl: string;
  category: 'help' | 'review' | 'discussion';
  tags: string[];
  engagement: 'low' | 'medium' | 'high';
  icon: string;
}

export const redditPosts: RedditPost[] = [
  {
    "id": "1oxl7hu",
    "title": "[HELP & DISCUSSION] Winter Burrow",
    "subreddit": "cozygames",
    "description": "Soft-lock solutions and progress bug help thread with 200+ replies",
    "url": "https://www.reddit.com/r/cozygames/comments/1oxl7hu/help_discussion_winter_burrow/",
    "redditUrl": "https://reddit.com/1oxl7hu",
    "category": "help",
    "tags": [
      "soft-lock",
      "bugs",
      "troubleshooting"
    ],
    "engagement": "high",
    "icon": "🆘"
  },
  {
    "id": "1ovh6xj",
    "title": "Winter Burrow Review: Cute and Cosy But Demands Patience",
    "subreddit": "NintendoSwitch",
    "description": "Comprehensive player review and experience mega-thread",
    "url": "https://www.reddit.com/r/NintendoSwitch/comments/1ovh6xj/winter_burrow_review_cute_and_cosy_but_demands/",
    "redditUrl": "https://reddit.com/1ovh6xj",
    "category": "review",
    "tags": [
      "review",
      "gameplay",
      "opinions"
    ],
    "engagement": "high",
    "icon": "⭐"
  },
  {
    "id": "1oey51d",
    "title": "Has anyone played the Winter Burrow demo?",
    "subreddit": "CozyGamers",
    "description": "CozyGamers community demo first impressions discussion",
    "url": "https://www.reddit.com/r/CozyGamers/comments/1oey51d/has_anyone_played_the_winter_burrow_demo/",
    "redditUrl": "https://reddit.com/1oey51d",
    "category": "discussion",
    "tags": [
      "demo",
      "first-impressions",
      "feedback"
    ],
    "engagement": "medium",
    "icon": "💬"
  },
  {
    "id": "1ovrm35",
    "title": "Winter Burrow. Is there a map in this game?",
    "subreddit": "cozygames",
    "description": "Discussion about the no-map exploration challenge and navigation tips",
    "url": "https://www.reddit.com/r/cozygames/comments/1ovrm35/winter_burrow_is_there_a_map_in_this_game/",
    "redditUrl": "https://reddit.com/1ovrm35",
    "category": "help",
    "tags": [
      "map",
      "navigation",
      "exploration"
    ],
    "engagement": "medium",
    "icon": "🆘"
  },
  {
    "id": "1ovmjea",
    "title": "I have no idea how to progress in Winter Burrow",
    "subreddit": "cozygames",
    "description": "New player progression help and community guidance",
    "url": "https://www.reddit.com/r/cozygames/comments/1ovmjea/i_have_no_idea_how_to_progress_in_winter_burrow/",
    "redditUrl": "https://reddit.com/1ovmjea",
    "category": "help",
    "tags": [
      "beginner",
      "progression",
      "guide"
    ],
    "engagement": "high",
    "icon": "🆘"
  }
];

export default redditPosts;
