// Auto-generated by scripts/fetch-youtube.js
// YouTube videos for Winter Burrow

export interface Video {
  id: string;
  title: string;
  description: string;
  url: string;
  embedUrl: string;
  thumbnail: string;
  thumbnailMedium: string;
  category: string;
  duration: string;
  source: string;
}

export const videos: Video[] = [
  {
    "id": "IARTw2JICZU",
    "title": "Winter Burrow – Announcement Trailer – Nintendo Switch",
    "description": "Official announcement trailer from Nintendo",
    "url": "https://www.youtube.com/watch?v=IARTw2JICZU",
    "embedUrl": "https://www.youtube.com/embed/IARTw2JICZU",
    "thumbnail": "https://img.youtube.com/vi/IARTw2JICZU/maxresdefault.jpg",
    "thumbnailMedium": "https://img.youtube.com/vi/IARTw2JICZU/mqdefault.jpg",
    "category": "trailer",
    "duration": "1 min",
    "source": "Nintendo Official"
  },
  {
    "id": "Huj0WmMRiMk",
    "title": "Is Winter Burrow Worth Playing? - In-Depth Review",
    "description": "Comprehensive 20-minute review of Winter Burrow gameplay, mechanics, and value",
    "url": "https://www.youtube.com/watch?v=Huj0WmMRiMk",
    "embedUrl": "https://www.youtube.com/embed/Huj0WmMRiMk",
    "thumbnail": "https://img.youtube.com/vi/Huj0WmMRiMk/maxresdefault.jpg",
    "thumbnailMedium": "https://img.youtube.com/vi/Huj0WmMRiMk/mqdefault.jpg",
    "category": "review",
    "duration": "20 min",
    "source": "Independent Reviewer"
  },
  {
    "id": "hQqV9lA9A94",
    "title": "WINTER BURROW Gameplay Walkthrough FULL GAME (No Commentary)",
    "description": "4K complete playthrough without commentary showing all gameplay elements",
    "url": "https://www.youtube.com/watch?v=hQqV9lA9A94",
    "embedUrl": "https://www.youtube.com/embed/hQqV9lA9A94",
    "thumbnail": "https://img.youtube.com/vi/hQqV9lA9A94/maxresdefault.jpg",
    "thumbnailMedium": "https://img.youtube.com/vi/hQqV9lA9A94/mqdefault.jpg",
    "category": "walkthrough",
    "duration": "Full Game",
    "source": "Gameplay Channel"
  }
];

// Export as featuredVideos for backwards compatibility
export const featuredVideos = videos;

export default videos;
